# update: 2024-01-26 V1.7.6
# 注释参数仅供示例使用, 此配置仅作模板使用，请勿在此文件直接更改，
name: FilterBwaMem2SortDup
fq_reader:
  # 是否开启校验, 填true/false 默认为[true] BOOL
  check: true
# 过滤Fq组件
filter:
  # 用分号;分隔, 支持批量文件输入，rg信息可选
  i:
    - fq: /data/lush-dev/yourui/Data/lush_aligner1/fq/r.1.fq;/data/lush-dev/yourui/Data/lush_aligner1/fq/r.2.fq
      rg: "@RG\\tID:id-1\\tSM:sm-2\\tLB:lib1\\tPL:MGI"
    - fq: /data/lush-dev/yourui/Data/lush_aligner1/fq/r.3.fq;/data/lush-dev/yourui/Data/lush_aligner1/fq/r.4.fq
      rg: "@RG\\tID:id-2\\tSM:sm-3\\tLB:lib2\\tPL:MGI"
  # 输出结果的路径
  o: /data/lush-dev/yourui/Data/lush_aligner1/out/filterbwamem2sortdup
  # fastq文件读取的批次大小,默认为默认为[80000] INT
  batch_size: 80000
  # 线程数 默认为[1] INT
  t: 10
  # 短序列接头
  adapter:
    - AAGTCGGAGGCCAAGCGGTCTTAGGAAGACAA
    - AAGTCGGATCGTAGCCATGTCGTTCTGTGAGCCAAGGAGTTG
  # adapter's shortest match ratio(default: [0.5])
  # m: 0.8
  # the max mismatch number when match the adapter(default: [1])
  # b: 2
  # low quality threshold(default: [5])
  l: 12
  # low quality rate(default: [0.5])
  q: 0.5
  # mean quality threshold(default: [0])
  # w: 20
  # N rate threshold(default: [0.05])
  n: 0.1
  # A rate threshold, 0 means not filter(default: [0])
  # a: 0.9
  # quality offset, for example: illumina18 is 33, 0 means infered by program(default: [0])
  s: 33
  # 是否合并统计Fq, 默认：false
  d: false
  # 截取fastQ文件总共的前n条，浮点数，单位 M(1000 * 1000). 默认为0, 表示不进行截取
  c: 0
  # trim开关，填true或者false，默认值 [false]
  adapter_trim: false
  # trim的最小长度，INT 默认值 [30]
  min_read_len: 30
  # trim字符串：STRING，格式 "INT, INT, INT, INT" 默认值 ["0, 0, 0, 0"]
  trim: "0, 0, 0, 0"

# 比对组件
bwa_mem2:
  # 参考序列路径
  index: /data/lush-dev/yourui/Data/ref/hg19/ref-new/hg19.fasta
  # 线程数
  t: 64
  # minimum seed length [19] INT
  # k: 19
  # band width for banded alignment [100] INT
  # w: 100
  # off-diagonal X-dropoff [100] INT
  # d: 100
  # look for internal seeds inside a seed longer than {-k} * FLOAT [1.5] FLOAT
  # r: 1.1
  # seed occurrence for the 3rd round seeding [20] INT
  # y: 20
  # skip seeds with more than INT occurrences [500] INT
  # c: 500
  # drop chains shorter than FLOAT fraction of the longest overlapping chain  [0.50] FLOAT
  # D: 0.50
  # discard a chain if seeded bases shorter than INT [0] INT
  # W: 0
  # perform at most INT rounds of mate rescues for each read [50] INT
  # m: 100
  # skip mate rescue [BOOL: true/false] [false]
  # S: false
  # skip pairing; mate rescue performed unless -S also in use [BOOL: true/false] [false]
  # P: false
  # score for a sequence match, which scales options -TdBOELU unless overridden [1] INT
  # A: 1
  # penalty for a mismatch [4] INT
  # B: 4
  # gap open penalties for deletions and insertions [6,6] INT[,INT]
  # O: 6,6
  # gap extension penalty; a gap of size k cost '{-O} + {-E}*k' [1,1] INT[,INT]
  # E: 1,1
  # penalty for 5'- and 3'-end clipping [5,5] INT[,INT]
  # L: 5,5
  # penalty for an unpaired read pair [17] INT
  # U: 17
  # read type. Setting -x changes multiple parameters unless overridden [null] STR
  # pacbio: -k17 -W40 -r10 -A1 -B1 -O1 -E1 -L0  (PacBio reads to ref)
  # ont2d: -k14 -W20 -r10 -A1 -B1 -O1 -E1 -L0  (Oxford Nanopore 2D-reads to ref)
  # intractg: -B9 -O16 -L5  (intra-species contigs to ref)
  # x:
  # smart pairing (ignoring in2.fq) [BOOL: true/false] [false]
  # p: false
  # insert STR to header if it starts with @; or insert lines in FILE [null] STR/FILE
  # H:
  # treat ALT contigs as part of the primary assembly (i.e. ignore <idxbase>.alt file) [BOOL: true/false] [false]
  # j: false
  # for split alignment, take the alignment with the smallest coordinate as primary [BOOL: true/false] [false]
  # 5: false
  # don't modify mapQ of supplementary alignments [BOOL: true/false] [false]
  # q: false
  # process INT input bases in each batch regardless of nThreads (for reproducibility) [] INT
  # K:
  # verbosity level: 1=error, 2=warning, 3=message, 4=debugging [3] INT
  # v: 3
  # minimum score to output [30] INT
  # T: 30
  # if there are <INT hits with score >80%% of the max score, output all in XA [5,200] INT[,INT]
  # h: 5,200
  # output all alignments for SE or unpaired PE [BOOL: true/false] [false]
  # a: false
  # append FASTA/FASTQ comment to SAM output [BOOL: true/false] [false]
  # C: false
  # output the reference FASTA header in the XR tag [BOOL: true/false] [false]
  # V: false
  # use soft clipping for supplementary alignments [BOOL: true/false] [false]
  # Y: false
  # mark shorter split hits as secondary [BOOL: true/false] [false]
  # M: false
  # specify the mean, standard deviation (10% of the mean if absent), max
  #                     (4 sigma from the mean if absent) and min of the insert size distribution.
  #                     FR orientation only. [inferred] FLOAT[,FLOAT[,INT[,INT]]]
  # I:

# 排序去重组件
sort_dup:
  # 同时生成Fragbam的线程数
  frag_bam_thread: 4
  # 一个Fragbam包含的bambatch个数
  frag_bam_size: 25
  # 输出结果的路径
  o: /data/lush-dev/yourui/Data/lush_aligner1/out/filterbwamem2sortdup/filterbwasortdup.bam
  # 线程数
  t: 64
  # 临时文件路径，需要有读写权限
  z: /data/lush-dev/yourui/Data/lush_aligner1/out/tmp
  # bam切分模式：0不切分,1只切分unmap,2按照染色体切分 [默认值：0]
  segment_mode: 0
  # 是否开启Bam去重 [默认值：true]
  is_mark_duplicate: true
  # tmp_sdb字段，0为原始bam格式，1为sdb压缩格式 [默认值：0]
  tmp_sdb: 0

